# Server Configuration
server.port=8082

# Application Name
spring.application.name=complaint-service

# Database Connection (Aiven Cloud MySQL)
spring.datasource.url=jdbc:mysql://sgsits-college-portal-db-sgsits-college-portal.e.aivencloud.com:25534/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_CfTyuEc3uqf1HxdWz0C

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Connection Pool Limit (Crucial for Cloud Free-Tiers)
spring.datasource.hikari.maximum-pool-size=3
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false